#REGRAS:
# 3 CARTAS IGUAIS > 2 CARTAS IGUAIS
# 3 CARTAS DE MAIOR VALOR > 2 CARTAS DE MENOR VALOR
# 2 CARTAS DE MAIOR VALOR > 2 CARTAS DE MENOR VALOR
# SE ESSAS CONDIÇÕES NÃO FOREM ATINGIDAS, UMA NOVA PARTIDA É INICIADA

# ALGORITMO
# RECEBER A DUAS PRIMEIRAS CARTAS
# VERIFICAR O MAIOR VALOR ENTRE A DUAS CARTAS
# O MAIOR VALOR É CARTA QUE MAXIMIZA A VITORIA
# IMPRIMIR A CARTA QUE MAXIMIZA O CHANCE DO JOGADOR GANHAR

#SUBPROGRAMA
def melhorCarta(ca1, ca2):
    if ca1 > ca2:
        return ca1
    else:
        return ca2

# PRINCIPAL
carta1, carta2 = map(int, input().split())
cartaDaVitoria = melhorCarta(carta1, carta2)
print(cartaDaVitoria)
